version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

  app:
    build: .
    restart: always
    environment:
      MONGO_URL: 'mongodb://root:rootpassword@mongo:27017/?retryWrites=true&w=majority'
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
